# Generated by Django 3.2.7 on 2021-09-19 07:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_todo_datetime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='datetime',
            field=models.DateTimeField(default=datetime.datetime(2021, 9, 19, 10, 35, 20, 163432)),
        ),
    ]
